cluster:
  directory: /home/rebeccac/scratch/spatial_matched_filter
  name: simulate_obs
  nodes: 16
  time: 30
  ompnum: 3
  pernode: 16
  mem: 192000M
  system: cedar
  queue_sys: slurm
  account: rrg-kmsmith
pipeline:
  logging:
    root: DEBUG
    peewee: INFO
    matplotlib: INFO
    h5py: INFO
  save_versions:
  - caput
  - cora
  - draco
  - drift
  - numpy
  - scipy
  - h5py
  - mpi4py
  tasks:
  - type: draco.core.task.SetMPILogging
    params:
      level_rank0: DEBUG
      level_all: WARN
  - type: draco.core.io.LoadProductManager
    out: manager
    params:
      product_directory: /home/rebeccac/scratch/beam_64_dec45
  - type: draco.core.io.LoadMaps
    out: map
    params:
      maps:
      - tag: HIgalaxies
        files:
        - /home/rebeccac/scratch/spatial_matched_filter/notebooks/input.h5
  - type: draco.synthesis.stream.SimulateSidereal
    requires: manager
    in: map
    out: sstack
    params:
      save: true
      output_name: /home/rebeccac/scratch/spatial_matched_filter/notebooks/sstream.h5
  - type: draco.analysis.transform.MModeTransform
    requires: manager
    in: sstack
    out: mmodes
  - type: draco.analysis.mapmaker.DirtyMapMaker
    requires: manager
    in: mmodes
    out: dirty_map
    params:
      nside: 64
      save: true
      output_name: /home/rebeccac/scratch/spatial_matched_filter/notebooks/dirty_map.h5
      